#!/bin/bash

DEST="/var/zxcvbn-data"

git clone https://github.com/dropbox/zxcvbn.git
coffee -cb zxcvbn/src/frequency_lists.coffee
nodejs -e "var frequency_lists = require('./zxcvbn/src/frequency_lists.js'); console.log( JSON.stringify( frequency_lists ) );" > $DEST/frequency_lists.json
php -r "\$f=json_decode(file_get_contents('$DEST/frequency_lists.json'));foreach(\$f as \$d=>\$l){\$r=array();foreach(\$l as \$k=>\$w){\$r[\$w]=\$k+1;}file_put_contents(sprintf('$DEST/ranked_frequency_list-%s.json',preg_replace('/[^\\w]/','',\$d)),json_encode(array(\$d=>\$r)));}"
coffee -cb zxcvbn/src/adjacency_graphs.coffee
nodejs -e "var adjacency_graphs = require('./zxcvbn/src/adjacency_graphs.js'); console.log( JSON.stringify( adjacency_graphs ) );" > $DEST/adjacency_graphs.json
rm -rf zxcvbn
rm $DEST/frequency_lists.json
